spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.file-size-threshold=1MB
spring.config.import=classpath:globals.properties

# Google OAuth2 \ub4f1\ub85d \uc815\ubcf4
spring.security.oauth2.client.registration.google.client-id=455202254961-ao4157r8q86a98svrvggc0409strjvfp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google.do
spring.security.oauth2.client.registration.google.scope=email,profile

# Google OAuth2 \uc81c\uacf5\uc790 \uc815\ubcf4 (\uc120\ud0dd - \uae30\ubcf8\uac12\uacfc \ub3d9\uc77c\ud558\ubbc0\ub85c \uc0dd\ub7b5 \uac00\ub2a5)
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

kakao.javascript.key=a6c9edd3bdf445005625dcfda0191156

api.isens.cgms-url=https://cgm.i-sens.com:10200/v1/public/cgms

blood.client.id=6e40317a-7072-49f7-8bfd-e738402d677e
blood.client.secret=cSiZ4u9uZqW7KCuYEi3CyhDPeA5Jf0BI7JHrw-TsoQM
blood.auth.url=https://accounts.i-sens.com/auth/authorize
blood.token.url=https://accounts.i-sens.com/oauth2/token
blood.sample.url=https://api.i-sens.com/v1/public/samples

ai.base=https://api.openai.com/v1
ai.key=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
ai.model=gpt-4o-mini
ai.timeoutSec=30



