// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()   //는 eprecated 되었으므로 제거
      //  maven { url 'https://jitpack.io' } // 🔥 JitPack 추가
    }
}

plugins {
    alias(libs.plugins.android.application) apply false
}
